name: Run build with tests

on:
  push:
    branches: [ main, rewrite-1.0.0 ]
  pull_request:
    branches: [ main, rewrite-1.0.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: 21
          cache: maven
      - name: Build medusa-ui with tests
        working-directory: ./medusa-ui
        run: mvn clean install --no-transfer-progress -D"spring.profiles.active"=dev
      - name: Build medusa-showcase with tests
        working-directory: ./medusa-showcase
        run: mvn -U clean install --no-transfer-progress -D"spring.profiles.active"=dev
