name: Run build with tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: maven
      - name: Build medusa-ui with tests
        working-directory: ./medusa-ui
        run: mvn clean install --no-transfer-progress -D"spring.profiles.active"=dev
      - name: Build medusa-showcase with tests
        working-directory: ./medusa-showcase
        run: mvn -U clean install --no-transfer-progress -D"spring.profiles.active"=dev